src/client/src/routes/Dashboard/Admin/AdminDashboard.jsx
src/client/src/routes/Dashboard/Admin/Contest/AllContest.jsx
src/client/src/routes/Dashboard/Admin/Contest/ContestLeaderboard.jsx
src/client/src/routes/Dashboard/Admin/Contest/UserSubmissions.jsx
src/client/src/routes/Dashboard/Admin/CreateChallenge/ChallengeDetails.jsx
src/client/src/routes/Dashboard/Admin/CreateChallenge/Settings.jsx
src/client/src/routes/Dashboard/Admin/CreateChallenge/TestCase.jsx
src/client/src/routes/Dashboard/Admin/CreateContest/AddChallenge.jsx
src/client/src/routes/Dashboard/Admin/CreateContest/ContestDetails.jsx
src/client/src/routes/Dashboard/Admin/CreateContest/SignUp.jsx
src/client/src/routes/Dashboard/User/Challenge/ChallengeLeaderboard.jsx
src/client/src/routes/Dashboard/User/Challenge/ContestChallenge.jsx
src/client/src/routes/Dashboard/User/Challenge/Runcode.jsx
src/client/src/routes/Dashboard/User/Challenge/SingleChallenge.jsx
src/client/src/routes/Dashboard/User/Challenge/SubmitCode.jsx
src/client/src/routes/Dashboard/User/Contest/TodayContest.jsx
src/client/src/routes/Dashboard/User/Profile/Profile.jsx
src/client/src/routes/Dashboard/User/UserDashboard.jsx

Created the file structure for frontend in context to user and admin:
Issue Link:https://github.com/masai-oss/execode/issues/7
Folders modified:src/client/src/routes/Dashboard/
Files modified: 
18 files changed
src/client/src/routes/Dashboard/Admin/AdminDashboard.jsx
src/client/src/routes/Dashboard/Admin/Contest/AllContest.jsx
src/client/src/routes/Dashboard/Admin/Contest/UserSubmissions.jsx
src/client/src/routes/Dashboard/Admin/CreateChallenge/ChallengeDetails.jsx
src/client/src/routes/Dashboard/Admin/CreateChallenge/Settings.jsx
src/client/src/routes/Dashboard/Admin/CreateChallenge/TestCase.jsx
src/client/src/routes/Dashboard/Admin/CreateContest/AddChallenge.jsx …

File_Structure_Updated

---

project_guide/EXECODE_API_DOCS.md

This is the Api Docs for execode.
**FIlename:EXECODE_API_DOCS.md(located under the project_guide folder)**
Sample format for Documentation.
​
GET `/challenge/<challenge_name>`
​
Required Headers - `Authorization: JWT <access_token>`
​
​
Success (Status Code - 200)
```json
{
"challenge_details":{
"description":"STRING",
"problem_statement":"STRING",
"input_format":"STRING",
"output_format":"STRING",
"constraints":"STRING",
"difficulty":"STRING",
"sample_input":"STRING",
"sample_output":"STRING",
"marks":"INTEGER",
},
"comment": "List of Challenges",
}
```
​
Issue for the documentation :https://github.com/masai-oss/execode/issues/11

Api Documentation for execode

---

src/client/public/index.html
src/client/src/components/common/LoginPublic.jsx
src/client/src/routes/Login.jsx

Added LoginPublic Component
issue link: #34 
File Modified
3 Files changed
/src/client/public/index.html
src/client/src/components/common/LoginPublic.jsx
src/client/src/routes/Login.jsx

Added LoginPublic Component 

---

src/client/public/index.html
src/client/src/components/AddChallenges/AddChallenges.jsx
src/client/src/components/AddTestCases/AddTestCases.jsx
src/client/src/components/ChallengeDetails/ChallengeDetails.jsx
src/client/src/components/ChallengeSettings/ChallengeSettings.jsx

Fixed Linting Errors of Previous Components
Issue Link : #45 
Files Modified 5
src/client/public/index.html
src/client/src/components/AddChallenges/AddChallenges.jsx
src/client/src/components/AddTestCases/AddTestCases.jsx
src/client/src/components/ChallengeDetails/ChallengeDetails.jsx
src/client/src/components/ChallengeSettings/ChallengeSettings.jsx

Fixed Linting Errors of Previous Components

---

src/client/src/routes/Dashboard/User/Contest/TodayContest.jsx

enhanced TodayContest page
Issue No. [36](https://github.com/masai-oss/execode/issues/36)
File location: src/routes/Dashboard/User/Contest/TodayContest.jsx

enhanced TodayContest page

---

.gitignore

Edited dependency in  .gitignore from node_modules to node_modules/
issue no. [40](https://github.com/masai-oss/execode/issues/40)
File location: execode/.gitignore

Edited dependency in  .gitignore to node_modules/

---

src/client/src/routes/Dashboard/User/Profile/Profile.jsx

enhanced : user profile page
issue no. [51](https://github.com/masai-oss/execode/issues/51)
1 file changed
File location:  src/routes/Dashboard/User/Profile/Profile.jsx

Designed user profile page

---

src/client/src/routes/Dashboard/Admin/CreateChallenge/CreateChallenge.jsx

Fixed Linting Errors of Previous Component
Issue Link:- #58 
Files Modified 1
src/client/src/routes/Dashboard/Admin/CreateChallenge/CreateChallenge.jsx

Fixed Linting errors for Previous Component

---

src/client/src/routes/Dashboard/Admin/CreateChallenge/ChallengeSetting.jsx

Added Admin ChallengeSetting.
issue No: #54
1 file added,
File location :- src/routes/Dashboard/Admin/CreateChallenge/ChallengeSetting.jsx

Admin ChallangeSetting Added

---

src/client/src/routes/Dashboard/Admin/CreateContest/CreateContest.jsx
src/client/src/routes/Dashboard/Dashboard.jsx
src/client/src/routes/Dashboard/NavBar.jsx
src/client/src/routes/Dashboard/Profile.jsx
src/client/src/routes/NavbarPublic.jsx
src/client/src/routes/Routes.jsx

Fixed Linting Errors of Previous Components and Application Theme As Been Changed
`src/client/src/routes/Dashboard/Admin/CreateContest/CreateContest.jsx`
`src/client/src/routes/Dashboard/Dashboard.jsx`
` src/client/src/routes/Dashboard/NavBar.jsx `
`src/client/src/routes/Dashboard/Profile.jsx`
` src/client/src/routes/Routes.jsx`

Fixed Linting Errors of Previous Components and Application Theme As Been Changed

---

src/client/src/routes/Dashboard/Admin/Contest/ContestLeaderboard.jsx
src/client/src/routes/Dashboard/Admin/Contest/UserSubmissions.jsx
src/client/src/routes/Dashboard/User/UserDashboard.jsx
src/server/app/main/routes/SubmittedCode.py
src/server/app/main/services/submitted_code_service.py
src/server/app/main/settings.py

issue no #61 
6 files changed
src/client/src/routes/Dashboard/Admin/Contest/UserSubmissions.jsx
src/client/src/routes/Dashboard/User/UserDashboard.jsx
src/server/app/main/routes/SubmittedCode.py
src/server/app/main/services/submitted_code_service.py
src/server/app/main/settings.py

submitted code back end api

---

src/client/src/components/common/LoginPublic.jsx
src/client/src/routes/Dashboard/Admin/CreateContest/SignUp.jsx
src/client/src/routes/Dashboard/User/UserDashboard.jsx
src/client/src/routes/Register.jsx

Created Signup form 
Issue Link [#14 ](https://github.com/masai-oss/execode/issues/14)
```
src/client/src/components/common/LoginPublic.jsx
src/client/src/routes/Dashboard/Admin/CreateContest/SignUp.jsx
src/client/src/routes/Dashboard/User/UserDashboard.jsx
src/client/src/routes/Register.jsx 
```

signup form created

---

src/client/src/routes/Dashboard/User/Challenge/SingleChallenge.jsx
src/client/src/routes/Dashboard/User/Challenge/SubmitCode.jsx
src/server/app/main/models/TestCasesModel.py
src/server/app/main/routes/AllChallenge.py
src/server/app/main/routes/Challengeroute.py
src/server/app/main/routes/__init__.py
src/server/app/main/services/alll_challenge.py
src/server/app/main/services/challenge.py
src/server/app/main/services/settings_services.py
src/server/app/main/services/tcs_services.py
src/server/app/main/utils/challeges_util.py

**This is add challenge from admin and getting all challenges from backend,getting a single challenge from backend .**
Issues:-
https://github.com/masai-oss/execode/issues/3
https://github.com/masai-oss/execode/issues/4
https://github.com/masai-oss/execode/issues/5
https://github.com/masai-oss/execode/issues/20
https://github.com/masai-oss/execode/issues/21
https://github.com/masai-oss/execode/issues/22
Files changed:
src/client/src/routes/Dashboard/User/Challenge/SingleChallenge.jsx
src/client/src/routes/Dashboard/User/Challenge/Submitcode.jsx
src/server/app/main/routes/AllChallenge.py
src/server/app/main/routes/Challengeroute.py
src/server/app/main/routes/__init__.py
src/server/app/main/services/alll_challenge.py
src/server/app/main/services/challenge.py …

Add_Challenge

---

src/server/app/main/routes/Contest.py
src/server/app/main/routes/Contests.py
src/server/app/main/services/contest_detail.py

**Create a contest.
Getting all contest
Getting all challenges for a contest**
Files:
Contest.py(route)
Contests.py(route to get all contests)
Contest_details.py(service)
**Issues**
https://github.com/masai-oss/execode/issues/73
https://github.com/masai-oss/execode/issues/72
https://github.com/masai-oss/execode/issues/6

Create Contest/ Getting all challenges for a contest 

---

src/client/src/components/AddTestCases/AddTestCases.jsx
src/client/src/components/ChallengeDetails/ChallengeDetails.jsx
src/client/src/routes/Dashboard/Admin/CreateChallenge/CreateChallenge.jsx

Fixed Errors on Previous Components
Issue Link:- #75 
Files Modified 3
src/client/src/components/ChallengeDetails/ChallengeDetails.jsx
src/client/src/components/AddTestCases/AddTestCases.jsx
src/client/src/routes/Dashboard/Admin/CreateChallenge/CreateChallenge.jsx

Fixed Errors on Previous Components

---

src/client/src/routes/Dashboard/Admin/CreateChallenge/CreateChallenge.jsx
src/client/src/utils/axiosInterceptor.js
src/server/app/main/routes/Challengeroute.py

**Creating the challenge modify** 
Added Axios to create challenge page
FIles changed:
src/server/app/main/routes/Challengeroute.py
src/client/src/utils/axiosInterceptor.js
src/client/src/routes/Dashboard/Admin/CreateChallenge/CreateChallenge.jsx

creating challenge axios added

---

src/client/src/routes/Dashboard/NavBar.jsx
src/client/src/routes/Dashboard/User/UserDashboard.jsx
src/client/src/routes/Register.jsx

issue link #90 
dashboard route fixed
` src/client/src/routes/Dashboard/NavBar.jsx`

dashboard route fixed

---

src/client/src/routes/Dashboard/Admin/AdminDashboard.jsx
src/client/src/routes/Register.jsx

Register page as been modified
issue link #102 
`src/client/src/routes/Register.jsx`

Register page & Admin Dashboard UI Modified

---

src/client/src/routes/Dashboard/Admin/Contest/AllContest.jsx
src/client/src/routes/Dashboard/Admin/Contest/ContestLeaderboard.jsx
src/client/src/routes/DashboardRoutes.jsx

issue no #101 
3 files changed
src/client/src/routes/Dashboard/Admin/Contest/AllContest.jsx
src/client/src/routes/DashboardRoutes.jsx

view submission routing done for all contest page

---

src/client/src/routes/Dashboard/Admin/Contest/ContestLeaderboard.jsx
src/client/src/routes/Dashboard/Admin/Contest/UserSubmissions.jsx

Added axios call to leader board and submissions.
Having local state for both these routes.
Also the code for submissions will display on proper response of code
Issue Link: #113 
Files Changed: 2
src/client/src/routes/Dashboard/Admin/Contest/UserSubmissions.jsx

Leader board Admin

---

src/client/src/routes/Dashboard/User/Contest/TodayContest.jsx

issue no #108 
1 file changed
src/client/src/routes/Dashboard/User/Contest/TodayContest.jsx

 Show all contests available to user

---

src/client/src/routes/Dashboard/User/Contest/ContestDetails.jsx
src/client/src/utils/axiosInterceptor.js

issue link #109 
Contest Details Done
` src/client/src/routes/Dashboard/User/Contest/ContestDetails.jsx `

Contest Details Page as Been Done

---

src/client/src/routes/Dashboard/User/Contest/ContestDetails.jsx

Contest Details Page Routes fixed
issue link #117 
` src/client/src/routes/Dashboard/User/Contest/ContestDetails.jsx `

Contest Details Page Routes fixed

---

src/client/src/routes/Dashboard/Admin/Contest/AllContest.jsx

issue no #112 
1 file changed
src/client/src/routes/Dashboard/Admin/Contest/AllContest.jsx

added end time removed slice

---

src/client/src/components/AddTestCases/AddTestCases.jsx
src/client/src/components/ChallengeDetails/ChallengeDetails.jsx
src/client/src/components/ChallengeSettings/ChallengeSettings.jsx
src/client/src/components/SingleContestItem/SingleContestItem.jsx
src/client/src/routes/Dashboard/Admin/CreateChallenge/CreateChallenge.jsx

Added validation to create challenge
Added two more fields sample_input and sample_output , which were missing
Fixed test case addition issue when switching tabs
Name of input file does not appear since using refs to handle files
Added new component to be used for single contest item
Issue Link : #121 
5 Files Modified:
src/client/src/components/AddTestCases/AddTestCases.jsx
src/client/src/components/ChallengeDetails/ChallengeDetails.jsx
src/client/src/components/ChallengeSettings/ChallengeSettings.jsx
src/client/src/components/SingleContestItem/SingleContestItem.jsx
src/client/src/routes/Dashboard/Admin/CreateChallenge/CreateChallenge.jsx

Added validation to create challenge

---

src/client/src/redux/authentication/reducer.js
src/client/src/routes/Dashboard/User/Challenge/SingleChallenge.jsx
src/client/src/utils/axiosInterceptor.js

Single Challenges page integration done

Single Challenges page integration

---

src/client/public/index.html
src/client/src/redux/authentication/reducer.js
src/client/src/routes/Dashboard/Admin/AdminDashboard.jsx
src/client/src/routes/Dashboard/NavBar.jsx
src/client/src/routes/Dashboard/User/Challenge/SingleChallenge.jsx
src/client/src/routes/Dashboard/User/Challenge/SubmitCode.jsx
src/client/src/routes/Dashboard/User/Contest/ContestDetails.jsx
src/client/src/routes/Home.jsx
src/client/src/routes/NavbarPublic.jsx
src/client/src/utils/axiosInterceptor.js

single page error has been fixed
issue link #126 
`src/client/src/routes/Dashboard/User/Challenge/SingleChallenge.jsx`

Challenge user page fixes

---

src/client/src/routes/Dashboard/Admin/Contest/AllContest.jsx
src/client/src/routes/Dashboard/User/Contest/ContestDetails.jsx
src/client/src/routes/Dashboard/User/Contest/TodayContest.jsx

user side UI has been modified
```
src/client/src/routes/Dashboard/Admin/Contest/AllContest.jsx 
src/client/src/routes/Dashboard/User/Contest/ContestDetails.jsx
src/client/src/routes/Dashboard/User/Contest/TodayContest.jsx
```

user side UI has been modified

---

src/client/src/components/AddChallenges/AddChallenges.jsx
src/client/src/components/AddTestCases/AddTestCases.jsx
src/client/src/routes/Dashboard/Admin/Contest/AllContest.jsx
src/client/src/routes/Dashboard/Admin/Contest/ContestLeaderboard.jsx
src/client/src/routes/Dashboard/Admin/CreateChallenge/CreateChallenge.jsx
src/client/src/routes/Dashboard/Admin/CreateContest/CreateContest.jsx
src/client/src/routes/Dashboard/User/Challenge/SingleChallenge.jsx
src/client/src/routes/Dashboard/User/Contest/ContestDetails.jsx
src/client/src/routes/Dashboard/User/Contest/TodayContest.jsx

admin side UI has been modified
```
src/client/src/components/AddChallenges/AddChallenges.jsx
src/client/src/components/AddTestCases/AddTestCases.jsx
src/client/src/routes/Dashboard/Admin/Contest/AllContest.jsx
src/client/src/routes/Dashboard/Admin/CreateChallenge/CreateChallenge.jsx 
src/client/src/routes/Dashboard/Admin/CreateContest/CreateContest.jsx
src/client/src/routes/Dashboard/User/Challenge/SingleChallenge.jsx
src/client/src/routes/Dashboard/User/Contest/ContestDetails.jsx 
src/client/src/routes/Dashboard/User/Contest/TodayContest.jsx
```

many UI changes to website

---

src/client/src/components/common/LoginPublic.jsx
src/client/src/routes/Register.jsx

login page and register page UI fixed
```
src/client/src/components/common/LoginPublic.jsx
src/client/src/routes/Register.jsx
```

login page and register page ui fixed

---

src/client/package.json
src/client/src/routes/Dashboard/User/Challenge/SubmitCode.jsx

run code  page UI has been updated
` src/client/src/routes/Dashboard/User/Challenge/SubmitCode.jsx`

SubmitCode page UI fix, package.json homepage fix

---

src/client/src/routes/Dashboard/User/Contest/ContestRegister.jsx

Contest Register Page
issue link #145 
` src/client/src/routes/Dashboard/User/Contest/ContestRegister.jsx `

Contest Register Page

---

src/client/src/routes/Dashboard/User/Challenge/ChallengeLeaderboard.jsx

Challenge Leaderboard Modified
issue Link #150 
`src/client/src/routes/Dashboard/User/Challenge/ChallengeLeaderboard.jsx
`

Challenge Leaderboard Modified

---

src/client/src/routes/Dashboard/Admin/Contest/UserSubmissions.jsx

User Submission Page Has been Modified
issue link #152 
`src/client/src/routes/Dashboard/Admin/Contest/UserSubmissions.jsx`

User Submission Page Has been Modified

---

src/client/src/redux/user/action.js
src/client/src/routes/Dashboard/Admin/Contest/UserSubmissions.jsx

UserSubmission UI has been Fixed
issue Link #152 
`src/client/src/routes/Dashboard/Admin/Contest/UserSubmissions.jsx `

UserSubmission UI has been Fixed

---

src/client/src/components/AddTestCases/AddTestCases.jsx
src/client/src/components/ChallengeDetails/ChallengeDetails.jsx

UI create challenge has been fixed
issue link #161 
`src/client/src/components/AddTestCases/AddTestCases.jsx`
`src/client/src/components/ChallengeDetails/ChallengeDetails.jsx`

UI create challenge has been fixed

---

src/client/src/routes/Dashboard/Admin/CreateContest/EditContestDetails.jsx
src/client/src/routes/DashboardRoutes.jsx

Added Edit contest page

---

src/client/src/routes/Dashboard/NavBar.jsx

I have made changes to logout as the button will act as mouse pointer on hover

logout button mouse pointer on hover

---

src/client/package-lock.json
src/client/public/index.html
src/client/src/components/common/LoginPublic.jsx
src/client/src/redux/admin/action.js
src/client/src/redux/admin/reducer.js
src/client/src/redux/authentication/actions.js
src/client/src/redux/authentication/reducer.js
src/client/src/redux/contest/reducer.js
src/client/src/redux/user/action.js
src/client/src/redux/user/reducer.js
src/client/src/routes/Dashboard/Admin/Contest/AllContest.jsx
src/client/src/routes/Dashboard/Profile.jsx
src/client/src/routes/Dashboard/User/Challenge/SingleChallenge.jsx
src/client/src/routes/Dashboard/User/Contest/ContestData.jsx
src/client/src/routes/Dashboard/User/Contest/ContestDetails.jsx
src/client/src/routes/Dashboard/User/Contest/ContestRegister.jsx
src/client/src/routes/Dashboard/User/Contest/Pagination.jsx
src/client/src/routes/Dashboard/User/Contest/TodayContest.jsx
src/client/src/routes/Dashboard/User/Contest/ViewSubmissions.jsx
src/client/src/routes/DashboardRoutes.jsx
src/client/src/routes/Register.jsx
src/client/src/routes/Routes.jsx
src/client/src/utils/axiosInterceptor.js

contest page updated, added new features contest signup, and contest user validation, updated contest routes `user` to `contest`

Contest Page Updated
